#!/usr/bin/env python
import sys
from BurrowsWheelerTransform import BurrowsWheelerTransform

if __name__ == "__main__":
    
    bwt = BurrowsWheelerTransform()
    encodedFile = bwt.invbwt(sys.stdin)
    sys.stdout.write(encodedFile)
